#!/usr/bin/env bash
set -e

XDEBUG_FLAGS=$(</var/run/s6/container_environment/XDEBUG_FLAGS)

exec /usr/sbin/php-fpm8 \
    --pid /var/run/xdebug/php-fpm8.pid \
    --prefix /var/run/xdebug \
    --fpm-config /etc/php8/php-fpm.conf \
    -d php_admin_value[zend_extension]=xdebug.so \
    -d zend_extension=xdebug.so \
    ${XDEBUG_FLAGS}
